### ISSUE TITLE
bug in train.py

### ISSUE THREAD

**Issue by ghost** [A-Jacobson/minimal-nmt#4]
Hi
could you please help with this bug, thanks

(transformer36) julia@vgne077:/idiap/user/julia/dev/temp_seq2seq/minimal-nmt$ python train.py 
  2%|██                                                                                                       | 1/50 [01:45<1:26:08, 105.48s/ epochsTraceback (most recent call last):                                                                                      | 0/907 [00:00<?, ? batches/s]
  File "train.py", line 23, in <module>
    train(seq2seq, optimizer, scheduler, train_iter, val_iter, num_epochs=hp.num_epochs)
  File "/remote/idiap.svm/user.active/julia/dev/temp_seq2seq/minimal-nmt/utils.py", line 71, in train
    loss.backward()
  File "/idiap/user/julia/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/idiap/user/julia/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cudnn RNN backward can only be called in training mode

**Comment by A-Jacobson** [comment]
I'm going to blindly guess this has something to do with your version of pytorch. This was built with 0.4. I have updated the setup to show that. If you aren't running this with pytorch 0.4. try that. If this bug is still happening I'm going to need more context as to how exactly you are using the project.
